edit_mode = "emacs"
startup = ["alias nutop  [] {cd /j/tmp24/nushell}", "alias nusrc  [] {cd /j/tmp24/nushell/src}", "alias  c [] {clear}", "alias  l [] {/bin/ls -al}", "alias  gls [] {git log --stat}", "alias  nuo [] {cd /j/tmp24/nushell-orig}"]
skip_welcome_message = true
